In [1]:
import numpy as np
arr1= np.array([10,20,30,40,50])
print(arr1)
print(arr1+2)
print(arr1*3)
print(arr1/2)


[10 20 30 40 50]
[12 22 32 42 52]
[ 30  60  90 120 150]
[ 5. 10. 15. 20. 25.]


In [2]:
arr2 = np.array([1,2,3,4,5,6])
reverse = arr2[::-1]
print(arr2)
print(reverse)

[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [10]:
 x = np.array([1,2,3,4,5,1,2,1,1,1])

 values,counts= np.unique(x,return_counts=True)
 mostfrequency=values[np.argmax(counts)]
 indices=np.where(x==mostfrequency)

 print(mostfrequency)
 print(np.max(counts))
 print(indices)

 y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

most_frequent = values[np.argmax(counts)]

indices = np.where(y == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Frequency:", np.max(counts))
print("Indices:", indices)



1
5
(array([0, 5, 7, 8, 9]),)
Most frequent value: 1
Frequency: 3
Indices: [0 1 2]


In [14]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])


20
70


In [18]:
arpit = np.linspace(10,100,25)
print(arpit.ndim)
print(arpit.shape)
print(arpit.size)
print(arpit.dtype)
print(arpit.nbytes)
w=arpit.reshape(1,25)
print(w)
v=arpit.reshape(1,25).T
print(v)

1
(25,)
25
float64
200
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [19]:
import numpy as np

ucs420_Arpit = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_Arpit)

# Mean
print("Mean:", np.mean(ucs420_Arpit))

# Median
print("Median:", np.median(ucs420_Arpit))

# Maximum
print("Maximum:", np.max(ucs420_Arpit))

# Minimum
print("Minimum:", np.min(ucs420_Arpit))

# Unique elements
print("Unique elements:", np.unique(ucs420_Arpit))

# Reshape into 4 rows and 3 columns
reshaped_ucs420_Arpit = ucs420_Arpit.reshape(4, 3)

print("Reshaped Array:")
print(reshaped_ucs420_Arpit)

# Resize into 2 rows and 3 columns
resized_ucs420_Arpit = np.resize(ucs420_Arpit, (2, 3))

print("Resized Array:")
print(resized_ucs420_Arpit)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array:
[[10 20 30]
 [40 50 60]]
