In [2]:
import numpy as np
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
temp = temperature +2
print(temp)

fahrenheit = 9/5 * temp + 32
print(fahrenheit)

above = temp[temp>32]
print(above)

count = np.sum(temp>32)

print(count)

[27 30 33 37 40 29 35 42]
[ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
[33 37 40 35 42]
5


In [3]:
steps = np.array([ [5000, 6200, 7100], [8000, 7500, 9000], [4500, 5100, 4800], [9000, 8500, 9500]])
print(np.sum(steps))
print(np.mean(steps))
print(np.max(steps))
print(np.min(steps))

print(np.sum(steps,axis=0))
print(np.sum(steps,axis=1))
print(np.argmax(steps))
print(np.unravel_index(np.argmax(steps), steps.shape))

84200
7016.666666666667
9500
4500
[26500 27300 30400]
[18300 24500 14400 27000]
11
(np.int64(3), np.int64(2))


In [4]:
arr = np.array([1,2,34,5,6])
subset = arr[1:5]
subset[0]=999
print(arr)
print(subset)
sub = arr[1:5].copy()
sub[0]=999

print(arr)
print(sub)

arr1 = np.arange(1,13).reshape(3,4)
print(arr1)

print(arr1[0,:])
print(arr1[-1,:])
print(arr1[:,1])
print(arr1[1:3,2:4])

flattened = arr1.flatten()
raveled = arr1.ravel()
print(flattened)
print(raveled)
raveled[0] = 1000
print(arr1)
print(raveled)
flattened[1] = 2000
print(arr1)
print(flattened)



print("\nProperties of original 3 x 4 matrix:")
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Size:", arr1.size)
print("Data type:", arr1.dtype)



[  1 999  34   5   6]
[999  34   5   6]
[  1 999  34   5   6]
[999  34   5   6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[ 9 10 11 12]
[ 2  6 10]
[[ 7  8]
 [11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
[1000    2    3    4    5    6    7    8    9   10   11   12]
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
[   1 2000    3    4    5    6    7    8    9   10   11   12]

Properties of original 3 x 4 matrix:
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [5]:

y = np.array([40, 65, 30, 85])


X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])


print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)



XT = X.T

print("\nTranspose of X:")
print(XT)


XTX = X.T @ X

print("\nX.T @ X:")
print(XTX)


XTX_inverse = np.linalg.inv(XTX)

print("\nInverse of X.T @ X:")
print(XTX_inverse)



beta = XTX_inverse @ X.T @ y

print("\nOLS Coefficients:")
print(beta)



print("\nCoefficients:")
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])



new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("\nPredicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2

Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS Coefficients:
[-0.15921454  0.14083853 10.06302242]

Coefficients:
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587

Predicted assistance score: 75.27862544779117
